# データの連結／結合

## データの連結／結合方法と関数／メソッド

### DataFrameの連結

### DataFrameの結合

## concat() 関数によるDataFrameの連結

In [1]:
from IPython.display import display
import pandas as pd

df1 = pd.DataFrame(
    [
        [1, 10, 100],
        [2, 20, 200],
        [3, 30, 300],
    ],
    index=list("abc"),
    columns=list("ABC"),
)
df2 = pd.DataFrame(
    [
        [4, 10, 100],
        [2, 20, 200],
        [3, 30, 400],
    ],
    index=list("acd"),
    columns=list("ACD"),
)
display(df1, df2)

   A   B    C
a  1  10  100
b  2  20  200
c  3  30  300

   A   C    D
a  4  10  100
c  2  20  200
d  3  30  400

In [2]:
pd.concat([df1, df2], ignore_index=True)

   A     B    C      D
0  1  10.0  100    NaN
1  2  20.0  200    NaN
2  3  30.0  300    NaN
3  4   NaN   10  100.0
4  2   NaN   20  200.0
5  3   NaN   30  400.0

In [3]:
labeled_df = pd.concat([df1, df2], keys=["data1", "data2"])
labeled_df

         A     B    C      D
data1 a  1  10.0  100    NaN
      b  2  20.0  200    NaN
      c  3  30.0  300    NaN
data2 a  4   NaN   10  100.0
      c  2   NaN   20  200.0
      d  3   NaN   30  400.0

## concat() 関数によるDataFrameの結合

In [6]:
pd.concat([df1, df2], axis=1)

     A     B      C    A     C      D
a  1.0  10.0  100.0  4.0  10.0  100.0
b  2.0  20.0  200.0  NaN   NaN    NaN
c  3.0  30.0  300.0  2.0  20.0  200.0
d  NaN   NaN    NaN  3.0  30.0  400.0

In [7]:
pd.concat([df1, df2], axis=1, join="inner")

   A   B    C  A   C    D
a  1  10  100  4  10  100
c  3  30  300  2  20  200

## join() メソッドによるDataFrameの結合

In [ ]:
df3 = pd.DataFrame(
    [[1.3, 10.3], [2.3, 20.3]],
    index=list("ab"),
    columns=list("DE"),
)
display(df1, df2, df3)

   A   B    C
a  1  10  100
b  2  20  200
c  3  30  300

   A   C    D
a  4  10  100
c  2  20  200
d  3  30  400

     D     E
a  1.3  10.3
b  2.3  20.3

In [9]:
df1.join(df3)

   A   B    C    D     E
a  1  10  100  1.3  10.3
b  2  20  200  2.3  20.3
c  3  30  300  NaN   NaN

In [10]:
df1.join(
    df2,
    how="inner",
    lsuffix="_df1",
    rsuffix="_df2",
)

   A_df1   B  C_df1  A_df2  C_df2    D
a      1  10    100      4     10  100
c      3  30    300      2     20  200

In [11]:
df4 = pd.DataFrame([["a", 1.4, 10.4], ["b", 2.4, 20.4]], columns=["key", "F", "G"])
display(df4, df1)

  key    F     G
0   a  1.4  10.4
1   b  2.4  20.4

   A   B    C
a  1  10  100
b  2  20  200
c  3  30  300

In [ ]:
df4.join(df1, on="key")

  key    F     G  A   B    C
0   a  1.4  10.4  1  10  100
1   b  2.4  20.4  2  20  200

## merge() メソッドによるDataFrameの結合

In [13]:
pd.merge(df1, df2, on="A")

   A   B  C_x  C_y    D
0  2  20  200   20  200
1  3  30  300   30  400

In [14]:
pd.merge(df1, df2, on="A", how="left")

   A   B  C_x   C_y      D
0  1  10  100   NaN    NaN
1  2  20  200  20.0  200.0
2  3  30  300  30.0  400.0

In [16]:
pd.merge(df1, df2, left_on="C", right_on="D")

   A_x   B  C_x  A_y  C_y    D
0    1  10  100    4   10  100
1    2  20  200    2   20  200

In [21]:
pd.merge(
    df1,
    df2,
    on="A",
    suffixes=("_df1", "_df2"),
)

   A   B  C_df1  C_df2    D
0  2  20    200     20  200
1  3  30    300     30  400

In [22]:
pd.merge(
    df1,
    df2,
    on="A",
    how="outer",
    indicator=True,
)

   A     B    C_x   C_y      D      _merge
0  1  10.0  100.0   NaN    NaN   left_only
1  2  20.0  200.0  20.0  200.0        both
2  3  30.0  300.0  30.0  400.0        both
3  4   NaN    NaN  10.0  100.0  right_only

In [23]:
pd.merge(
    df1,
    df2,
    how="cross",
    suffixes=("_df1", "_df2")
)

   A_df1   B  C_df1  A_df2  C_df2    D
0      1  10    100      4     10  100
1      1  10    100      2     20  200
2      1  10    100      3     30  400
3      2  20    200      4     10  100
4      2  20    200      2     20  200
5      2  20    200      3     30  400
6      3  30    300      4     10  100
7      3  30    300      2     20  200
8      3  30    300      3     30  400

In [24]:
import numpy as np

pd.merge(
    pd.DataFrame({"a": [np.nan, 1, 2]}),
    pd.DataFrame({"a": [1, 3, np.nan, np.nan]})
)

     a
0  NaN
1  1.0
2  NaN

### 重複したキーの検証

In [26]:
df5 = pd.DataFrame(
    [
        [1, 10, 100],
        [2, 20, 200],
        [2, 20, 200],
    ],
    index=list("abc"),
    columns=list("ABC"),
)
df5

   A   B    C
a  1  10  100
b  2  20  200
c  2  20  200

In [27]:
pd.merge(df1, df5, on="A", validate="one_to_one")

MergeError: Merge keys are not unique in right dataset; not a one-to-one merge

In [29]:
pd.merge(
    df1,
    df5,
    on="A",
    validate="one_to_many",
)

   A  B_x  C_x  B_y  C_y
0  1   10  100   10  100
1  2   20  200   20  200
2  2   20  200   20  200

### 近い値での結合

In [30]:
rng = np.random.default_rng(1)

def generate_date_range(size):
    return pd.date_range(
        "2022-01-01",
        freq="1s",
        periods=size,
    ) + pd.Series(rng.integers(0, 1000, size=size)).map(lambda x: pd.Timedelta(x, "ms"))

ts_df1 = pd.DataFrame(
    {
        "timestamp": generate_date_range(10),
        "data": rng.random(size=10),
    }
)
ts_df2 = pd.DataFrame(
    {
        "timestamp": generate_date_range(10),
        "data": rng.random(size=10),
    }
)
ts_df2 = pd.DataFrame(
    {
        "timestamp": generate_date_range(10),
        "data": rng.random(size=10),
    }
)
display(ts_df1, df2)

                timestamp      data
0 2022-01-01 00:00:00.473  0.423326
1 2022-01-01 00:00:01.511  0.827703
2 2022-01-01 00:00:02.755  0.409199
3 2022-01-01 00:00:03.950  0.549594
4 2022-01-01 00:00:04.034  0.027559
5 2022-01-01 00:00:05.144  0.753513
6 2022-01-01 00:00:06.822  0.538143
7 2022-01-01 00:00:07.948  0.329732
8 2022-01-01 00:00:08.249  0.788429
9 2022-01-01 00:00:09.311  0.303195

   A   C    D
a  4  10  100
c  2  20  200
d  3  30  400

In [ ]:
rng = np.random.default_rng(1)


def generate_date_range(size):
    return pd.date_range(
        "2022-01-01",
        freq="1s",
        periods=size,
    ) + pd.Series(rng.integers(0, 1000, size=size)).map(lambda x: pd.Timedelta(x, "ms"))


ts_df1 = pd.DataFrame(
    {
        "timestamp": generate_date_range(10),
        "data": rng.random(size=10),
    }
)
ts_df2 = pd.DataFrame(
    {
        "timestamp": generate_date_range(10),
        "data": rng.random(size=10),
    }
)
display(ts_df1, ts_df2)

                timestamp      data
0 2022-01-01 00:00:00.473  0.423326
1 2022-01-01 00:00:01.511  0.827703
2 2022-01-01 00:00:02.755  0.409199
3 2022-01-01 00:00:03.950  0.549594
4 2022-01-01 00:00:04.034  0.027559
5 2022-01-01 00:00:05.144  0.753513
6 2022-01-01 00:00:06.822  0.538143
7 2022-01-01 00:00:07.948  0.329732
8 2022-01-01 00:00:08.249  0.788429
9 2022-01-01 00:00:09.311  0.303195

                timestamp      data
0 2022-01-01 00:00:00.124  0.750365
1 2022-01-01 00:00:01.453  0.280409
2 2022-01-01 00:00:02.976  0.485191
3 2022-01-01 00:00:03.134  0.980737
4 2022-01-01 00:00:04.383  0.961657
5 2022-01-01 00:00:05.403  0.724790
6 2022-01-01 00:00:06.903  0.541227
7 2022-01-01 00:00:07.203  0.276891
8 2022-01-01 00:00:08.502  0.160652
9 2022-01-01 00:00:09.262  0.969925

In [31]:
pd.merge_asof(
    ts_df1,
    ts_df2,
    on="timestamp",
    tolerance=pd.Timedelta("2s"),
)

                timestamp    data_x    data_y
0 2022-01-01 00:00:00.473  0.423326  0.917298
1 2022-01-01 00:00:01.511  0.827703  0.917298
2 2022-01-01 00:00:02.755  0.409199  0.528589
3 2022-01-01 00:00:03.950  0.549594  0.459336
4 2022-01-01 00:00:04.034  0.027559  0.459336
5 2022-01-01 00:00:05.144  0.753513  0.062350
6 2022-01-01 00:00:06.822  0.538143  0.852633
7 2022-01-01 00:00:07.948  0.329732  0.592941
8 2022-01-01 00:00:08.249  0.788429  0.592941
9 2022-01-01 00:00:09.311  0.303195  0.260097

In [38]:
pd.merge_asof(
    ts_df1,
    ts_df2,
    on="timestamp",
    tolerance=pd.Timedelta("2s"),
)

                timestamp    data_x    data_y
0 2022-01-01 00:00:00.473  0.423326  0.917298
1 2022-01-01 00:00:01.511  0.827703  0.917298
2 2022-01-01 00:00:02.755  0.409199  0.528589
3 2022-01-01 00:00:03.950  0.549594  0.459336
4 2022-01-01 00:00:04.034  0.027559  0.459336
5 2022-01-01 00:00:05.144  0.753513  0.062350
6 2022-01-01 00:00:06.822  0.538143  0.852633
7 2022-01-01 00:00:07.948  0.329732  0.592941
8 2022-01-01 00:00:08.249  0.788429  0.592941
9 2022-01-01 00:00:09.311  0.303195  0.260097