# RDBデータ

## SQLite3

## データサンプル

# sqlite3モジュールを使う

In [2]:
import sqlite3

con = sqlite3.connect("data/sakila-sqlite3/sakila_master.db")  # ・・①

In [4]:
cur = con.cursor()  # コネクションからカーソルオブジェクトを取得 ・・②
# select文を実行してfor文で順次データを取得
for table in cur.execute(  #  ・・③
    "SELECT name FROM sqlite_master WHERE type='table';"
):
    print(table[0])  # ・・④

actor
country
city
address
language
category
customer
film
film_actor
film_category
film_text
inventory
staff
store
payment
rental

In [ ]:
cur.execute("SELECT count(*) FROM film;")
cur.fetchall()

In [12]:
cur.execute("SELECT count(*) FROM inventory;")
cur.fetchall()

[(4581,)]

In [ ]:
for data in cur.execute(
    "SELECT FILM_ID, TITLE, RELEASE_YEAR, LENGTH, LAST_UPDATE FROM film LIMIT 10;"
):
    print(data)

In [17]:
limit = 5

for data in cur.execute(
    "SELECT FILM_ID, TITLE, RELEASE_YEAR, LENGTH, LAST_UPDATE"
    " FROM film LIMIT (?);",
    (limit,),
):
    print(data)

(1, 'ACADEMY DINOSAUR', '2006', 86, '2020-12-23 07:12:31')
(2, 'ACE GOLDFINGER', '2006', 48, '2020-12-23 07:12:31')
(3, 'ADAPTATION HOLES', '2006', 50, '2020-12-23 07:12:31')
(4, 'AFFAIR PREJUDICE', '2006', 117, '2020-12-23 07:12:31')
(5, 'AFRICAN EGG', '2006', 130, '2020-12-23 07:12:31')

In [19]:
limit = 5

for data in cur.execute(
    "SELECT FILM_ID, TITLE, RELEASE_YEAR, LENGTH, LAST_UPDATE"
    " FROM film LIMIT (?);",
    (limit,),
):
    print(data)

(1, 'ACADEMY DINOSAUR', '2006', 86, '2020-12-23 07:12:31')
(2, 'ACE GOLDFINGER', '2006', 48, '2020-12-23 07:12:31')
(3, 'ADAPTATION HOLES', '2006', 50, '2020-12-23 07:12:31')
(4, 'AFFAIR PREJUDICE', '2006', 117, '2020-12-23 07:12:31')
(5, 'AFRICAN EGG', '2006', 130, '2020-12-23 07:12:31')

In [22]:
limit = 20

for data in cur.execute(
    "SELECT F.FILM_ID, F.TITLE, F.RELEASE_YEAR, F.LENGTH, F.LAST_UPDATE, C.NAME"
    " FROM film as F"
    " LEFT JOIN film_category as FC ON F.FILM_ID = FC.FILM_ID"
    " LEFT JOIN category as C ON FC.CATEGORY_ID = C.CATEGORY_ID"
    " ORDER BY F.TITLE"
    " LIMIT (?);",
    (limit,),
):
    print(data)

(1, 'ACADEMY DINOSAUR', '2006', 86, '2020-12-23 07:12:31', 'Documentary')
(2, 'ACE GOLDFINGER', '2006', 48, '2020-12-23 07:12:31', 'Horror')
(3, 'ADAPTATION HOLES', '2006', 50, '2020-12-23 07:12:31', 'Documentary')
(4, 'AFFAIR PREJUDICE', '2006', 117, '2020-12-23 07:12:31', 'Horror')
(5, 'AFRICAN EGG', '2006', 130, '2020-12-23 07:12:31', 'Family')
(6, 'AGENT TRUMAN', '2006', 169, '2020-12-23 07:12:31', 'Foreign')
(7, 'AIRPLANE SIERRA', '2006', 62, '2020-12-23 07:12:31', 'Comedy')
(8, 'AIRPORT POLLOCK', '2006', 54, '2020-12-23 07:12:31', 'Horror')
(9, 'ALABAMA DEVIL', '2006', 114, '2020-12-23 07:12:31', 'Horror')
(10, 'ALADDIN CALENDAR', '2006', 63, '2020-12-23 07:12:31', 'Sports')
(11, 'ALAMO VIDEOTAPE', '2006', 126, '2020-12-23 07:12:31', 'Foreign')
(12, 'ALASKA PHANTOM', '2006', 136, '2020-12-23 07:12:31', 'Music')
(13, 'ALI FOREVER', '2006', 150, '2020-12-23 07:12:31', 'Horror')
(14, 'ALICE FANTASIA', '2006', 94, '2020-12-23 07:12:32', 'Classics')
(15, 'ALIEN CENTER', '2006', 46, '2020-12-23 07:12:32', 'Foreign')
(16, 'ALLEY EVOLUTION', '2006', 180, '2020-12-23 07:12:32', 'Foreign')
(17, 'ALONE TRIP', '2006', 82, '2020-12-23 07:12:32', 'Music')
(18, 'ALTER VICTORY', '2006', 57, '2020-12-23 07:12:32', 'Animation')
(19, 'AMADEUS HOLY', '2006', 113, '2020-12-23 07:12:32', 'Action')
(20, 'AMELIE HELLFIGHTERS', '2006', 79, '2020-12-23 07:12:32', 'Music')

# pandasを使う

In [34]:
import pandas as pd

df = pd.read_sql(
    "SELECT F.FILM_ID, F.TITLE, F.RELEASE_YEAR, F.LENGTH, F.LAST_UPDATE, C.NAME"
    " FROM film as F"
    " LEFT JOIN film_category as FC ON F.FILM_ID = FC.FILM_ID"
    " LEFT JOIN category as C ON FC.CATEGORY_ID = C.CATEGORY_ID",
    con=con,
    parse_dates=["last_update"],
)
df.head()

,film_id,title,release_year,length,last_update,name
0,1,ACADEMY DINOSAUR,2006,86,2020-12-23 07:12:31,Documentary
1,2,ACE GOLDFINGER,2006,48,2020-12-23 07:12:31,Horror
2,3,ADAPTATION HOLES,2006,50,2020-12-23 07:12:31,Documentary
3,4,AFFAIR PREJUDICE,2006,117,2020-12-23 07:12:31,Horror
4,5,AFRICAN EGG,2006,130,2020-12-23 07:12:31,Family

In [35]:
df.shape

(1000, 6)

In [37]:
df.dtypes

film_id                  int64
title                   object
release_year            object
length                   int64
last_update     datetime64[ns]
name                    object
dtype: object

In [ ]:
con.close()  # コネクションを閉じる