# CSV形式

## CSV形式のデータを扱う

## データサンプル

## テキストファイルとして読み込む

In [10]:
with open("data/FEH_00200524_230205124938.csv", "r", encoding="cp932") as f:  # ・・①
    for i, row in enumerate(f):  # ・・②
        for col in row.strip().split(","):  # ・・③
            print(col, end="|")  # ・・④
        print()
        print("===")
        if i > 1:  # ・・⑤
            break

"表章項目"|"人口"|"概算値"|"全国"|"時間軸（年月日現在）"|"年齢5歳階級"|"/男女別"|"男女計"|"男"|"女"|
===
"人口【万人】"|"総人口"|"概算値"|"全国"|"2021年12月"|"総数"|""|"12|547"|"6|099"|"6|448"|
===
"人口【万人】"|"総人口"|"概算値"|"全国"|"2021年12月"|"0～4歳"|""|"437"|"224"|"214"|
===

## pandasを使う

In [11]:
import pandas as pd

df = pd.read_csv("data/FEH_00200524_230205124938.csv", encoding="cp932")

In [12]:
df.head()

     表章項目   人口  概算値  全国 時間軸（年月日現在）  年齢5歳階級  /男女別     男女計      男      女
0  人口【万人】  総人口  概算値  全国   2021年12月      総数   NaN  12,547  6,099  6,448
1  人口【万人】  総人口  概算値  全国   2021年12月    0～4歳   NaN     437    224    214
2  人口【万人】  総人口  概算値  全国   2021年12月    5～9歳   NaN     503    258    245
3  人口【万人】  総人口  概算値  全国   2021年12月  10～14歳   NaN     535    274    261
4  人口【万人】  総人口  概算値  全国   2021年12月  15～19歳   NaN     559    287    272

In [13]:
df.tail()

       表章項目   人口  概算値  全国 時間軸（年月日現在）       年齢5歳階級  /男女別    男女計      男      女
373  人口【万人】  総人口  概算値  全国    2023年1月    （再掲）15歳未満   NaN  1,445    740    705
374  人口【万人】  総人口  概算値  全国    2023年1月   （再掲）15～64歳   NaN  7,411  3,755  3,657
375  人口【万人】  総人口  概算値  全国    2023年1月    （再掲）65歳以上   NaN  3,621  1,571  2,050
376  人口【万人】  総人口  概算値  全国    2023年1月  （再掲）うち75歳以上   NaN  1,953    773  1,179
377  人口【万人】  総人口  概算値  全国    2023年1月  （再掲）うち85歳以上   NaN    665    214    451

In [14]:
df.shape

(378, 10)

In [15]:
df.dtypes

表章項目           object
人口             object
概算値            object
全国             object
時間軸（年月日現在）     object
年齢5歳階級         object
/男女別          float64
男女計            object
男              object
女              object
dtype: object

### データ型を変換して取り込む

In [18]:
df_parsed = pd.read_csv(
    "data/FEH_00200524_230205124938.csv",
    encoding="cp932",
    parse_dates=["時間軸（年月日現在）"],
    date_format="%Y年%m月",
    thousands=",",
)
df_parsed.head()

     表章項目   人口  概算値  全国 時間軸（年月日現在）  年齢5歳階級  /男女別    男女計     男     女
0  人口【万人】  総人口  概算値  全国 2021-12-01      総数   NaN  12547  6099  6448
1  人口【万人】  総人口  概算値  全国 2021-12-01    0～4歳   NaN    437   224   214
2  人口【万人】  総人口  概算値  全国 2021-12-01    5～9歳   NaN    503   258   245
3  人口【万人】  総人口  概算値  全国 2021-12-01  10～14歳   NaN    535   274   261
4  人口【万人】  総人口  概算値  全国 2021-12-01  15～19歳   NaN    559   287   272

In [21]:
df_parsed.dtypes

表章項目                  object
人口                    object
概算値                   object
全国                    object
時間軸（年月日現在）    datetime64[ns]
年齢5歳階級                object
/男女別                 float64
男女計                    int64
男                      int64
女                      int64
dtype: object

### read_csvの便利なオプション

## csvモジュールを使う

In [20]:
import csv

with open(
    "data/FEH_00200524_230205124938.csv",
    "r",
    encoding="cp932",
    newline="",
) as f:
    data = csv.reader(f)
    for i, row in enumerate(data):
        for col in row:
            print(col, end="|")
        print()
        print("===")
        if i > 1:
            break

表章項目|人口|概算値|全国|時間軸（年月日現在）|年齢5歳階級|/男女別|男女計|男|女|
===
人口【万人】|総人口|概算値|全国|2021年12月|総数||12,547|6,099|6,448|
===
人口【万人】|総人口|概算値|全国|2021年12月|0～4歳||437|224|214|
===

In [24]:
import csv

with open(
    "data/FEH_00200524_230205124938.csv",
    "r",
    encoding="cp932",
    newline="",
) as f:
    data = csv.reader(f)
    for i, row in enumerate(data):
        for col in row:
            print(col, end="|")
        print()
        print("===")
        if i > 1:
            break

表章項目|人口|概算値|全国|時間軸（年月日現在）|年齢5歳階級|/男女別|男女計|男|女|
===
人口【万人】|総人口|概算値|全国|2021年12月|総数||12,547|6,099|6,448|
===
人口【万人】|総人口|概算値|全国|2021年12月|0～4歳||437|224|214|
===