# parquet形式

## pickle形式との違い

## `pandas`での利用

In [1]:
import pandas as pd

df_from_csv = pd.read_csv(
    "data/FEH_00200524_230205124938.csv",
    encoding="cp932",
    parse_dates=["時間軸（年月日現在）"],
    date_format="%Y年%m月",
    thousands=",",
)

df_from_csv.to_parquet("data/population-202302.parquet")
df_from_csv.head()

     表章項目   人口  概算値  全国 時間軸（年月日現在）  年齢5歳階級  /男女別    男女計     男     女
0  人口【万人】  総人口  概算値  全国 2021-12-01      総数   NaN  12547  6099  6448
1  人口【万人】  総人口  概算値  全国 2021-12-01    0～4歳   NaN    437   224   214
2  人口【万人】  総人口  概算値  全国 2021-12-01    5～9歳   NaN    503   258   245
3  人口【万人】  総人口  概算値  全国 2021-12-01  10～14歳   NaN    535   274   261
4  人口【万人】  総人口  概算値  全国 2021-12-01  15～19歳   NaN    559   287   272

In [2]:
df_from_parquet = pd.read_parquet("data/population-202302.parquet")
df_from_parquet.head()

     表章項目   人口  概算値  全国 時間軸（年月日現在）  年齢5歳階級  /男女別    男女計     男     女
0  人口【万人】  総人口  概算値  全国 2021-12-01      総数   NaN  12547  6099  6448
1  人口【万人】  総人口  概算値  全国 2021-12-01    0～4歳   NaN    437   224   214
2  人口【万人】  総人口  概算値  全国 2021-12-01    5～9歳   NaN    503   258   245
3  人口【万人】  総人口  概算値  全国 2021-12-01  10～14歳   NaN    535   274   261
4  人口【万人】  総人口  概算値  全国 2021-12-01  15～19歳   NaN    559   287   272

In [4]:
df_from_parquet.equals(df_from_csv)

True

In [8]:
import os

# parquet形式
os.path.getsize("data/population-202302.parquet")

11587

In [9]:
# pickle形式
df_from_csv.to_pickle("data/population-202302.pickle")
os.path.getsize("data/population-202302.pickle")

20641